Add some option error message informations

diff --git a/aeten-ads b/aeten-ads
--- a/aeten-ads
+++ b/aeten-ads
@@ -3,7 +3,7 @@
 # Depends:
 # bin: bash cat cut sed(GNU) grep man groff
 # debian: bash coreutils grep man-db groff-base
-input=$(sed 's/'"'"'/\\[u0027]/g; s/`/\\[u0060]/g; s/\$/\\[u0024]/g; s/  / \\ /g' /dev/stdin)
+input=$(sed 's/'"'"'/\\[u0027]/g; s/`/\\[u0060]/g; s/\$/\\[u0024]/g; s/  / \\ /g; s/\\%/\\[u005C]%/g' /dev/stdin)
 
 aeten_ads_init() {
 	local args=${@}
@@ -150,7 +150,7 @@ aeten_ads_usage() {
 	shift
 	groff -T utf8 -man << EOF | sed '/^\s*$/d;/\s*()/d;/()\s*()/d' >/dev/fd/$([ ${errno} -eq 0 ] && echo 1 || echo 2)
 .TH
-.SH Usage:
+.SH $@ Usage:
 .SY $(basename ${script})
 $(aeten_ads_foreach_option aeten_ads_synopsys_man)
 EOF
@@ -240,7 +240,7 @@ EOF
 }
 
 __aeten_ads_wrong_option() {
-		echo "-*) $(readlink -f ${0}) usage ${name} 1 <<< '$(echo "${input}"|sed $"s/\$/\\\\x0/")'; exit 1;;"
+		echo "-*) $(readlink -f ${0}) usage ${name} 1 "Invalid option \"'${1}'\"" <<< '$(echo "${input}"|sed $"s/\$/\\\\x0/")'; exit 1;;"
 }
 
 __aeten_ads_man_section() {
@@ -255,7 +255,7 @@ __aeten_ads_check_option() {
 	local _varname
 	if ${requiered}; then
 		_varname=${_var_prefix}$(echo ${option}|tr '[:lower:]' '[:upper:]'|tr - _)
-		echo "[ -z \${${_varname}+x} ] && { $(readlink -f ${0}) usage ${name} 1 <<< '$(echo "${input}"|sed $"s/\$/\\\\x0/")'; exit 1; };"
+		echo "[ -z \${${_varname}+x} ] && { $(readlink -f ${0}) usage ${name} 1 "Option ${option} is requiered." <<< '$(echo "${input}"|sed $"s/\$/\\\\x0/")'; exit 1; };"
 	fi
 }
 
